name: Livssnyter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40096
title: Livssnyter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.970650605391711
  lightness: 0.6830873214639723
  saturation: 0.10839940258301795
  rhythmicContrast: 0.5
purpose: []
